apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
spec:
  containers:
    - image: registry.localhost/tomcat:latest
      name: simple-pod
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
